### ISSUE TITLE
Persisting visualizations zoom when saving analysis

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#367] opened 2022-03-21 07:02 UTC
As a User I want visualizations zoom to be persisted so I do not have to configure it every time after reload.

**Comment by skalkin** [comment] 2022-03-22 20:45
Implemented for scatter plot in v0.139
Current viewport is only saved (and then applied) if a user zooms in.
I suspect there will be many corner issues associated with this feature, but let's use it as a starting step...

**Comment by RobertStrulak** [comment] 2022-03-25 07:42
Hi Andrew,
Thanks for the update! I've sent you an email with some questions.

Robert

**Comment by RobertStrulak** [comment] 2022-04-11 15:37
Hi Andrew,
We played a bit with this feature and definitely there are many corner cases...

In the first (or actually second) iteration it would be great if you could implement following behavior:

Option: **no action**
- No changes to axes and zoom sliders upon filtering, restoring, etc.
- Filtering is reflected (for instance on the ScatterPlot markers disappear after applying filters - still no changes to axes and zoom sliders)

Questions:
- Can we make the "no action" option the default one?

**Comment by RobertStrulak** [comment] 2022-04-12 15:16
@RobertStrulak  - to attach a video with examples

**Comment by RobertStrulak** [comment] 2022-04-13 12:17
@skalkin - please find attached a video.

Steps to reproduce:
1. Add a ScatterPlot (Zoom and Filter = **no option**), modify zoom sliders and save the project
2. Reload the page
3. Opening of the filter panel results in resetting previously stored positions of zoom sliders

![CC70BFFD-2365-403C-A896-8AC565E1C62A](https://user-images.githubusercontent.com/99964535/163177429-86546b36-6628-4ada-8370-dba8b981569d.GIF)

**Comment by skalkin** [comment] 2022-04-26 10:51
Made the `zoom and filter: no action` value override the `axis follow filter` property. And yes, we can make the `no action` option the default one, but all these previously implemented options like `axes follow filter` and `zoom by filter` that are on by default were also requested by NIBR - are you sure you want them to go away?

**Comment by RobertStrulak** [comment] 2022-05-02 20:01
Hi @skalkin 
Which version does include the fix? I've just checked on our env (version 0.150.1) and apart from the issue mentioned by Ekaterina the case described by me (post from April 13th) is still reproducible.

**Comment by skalkin** [comment] 2022-05-03 11:40
This is happening because the "axes follow filter" property is set to true, so when the (default) filter gets added it resets the filter. Not sure what the desired behavior should be, should we adjust the filter to the viewport defined by the scatter plot? What if there are two scatter plots?

**Comment by skalkin** [comment] 2022-05-03 11:42
If "no action" is set (like was requested by you), the scatter plot does not get reset (but it also does not filter the rows)

**Comment by RobertStrulak** [comment] 2022-05-04 07:57
Hi @skalkin , @alex-aprm 
I've checked once again and the issue reported by @katerina-stepanova is still reproducible.

**Steps to reproduce:**
1. Add a Scatter Plot (Zoom And Filter: no action; Axes Follow Filter: disabled)
2. Modify zoom sliders on the Scatter Plot
3. Open the filter panel and do some filtering
4. Save the project
5. Reload page

**Expected behavior:**
Zoom sliders are persisted and restored after page reload. 

**Current behavior:**
When the filter panel is opened and some filtering is applied to state of Zoom sliders is not persisted.

After save:
![Snag_88c6f4](https://user-images.githubusercontent.com/99964535/166642467-b1260122-7604-44c2-b8ea-2fbd81dc4850.png)

After reload:
![Snag_88f6dd](https://user-images.githubusercontent.com/99964535/166642494-9aac7716-a9a1-465a-aa7c-1cdd5d4bf4c9.png)

**Comment by skalkin** [comment] 2022-05-05 20:47
Hi @RobertStrulak , this is what I see when I reproduce the steps you've described on dev - everything works as expected. Which version are you testing it on?

![scatter-plot-zoom-persistence](https://user-images.githubusercontent.com/943403/167022738-a0abc249-dc73-461d-9347-405ce682a73f.gif)

**Comment by skalkin** [comment] 2022-05-05 21:32
Fixed in v150.7

Looks like I have found the issue - the root of the problem was that the _categorical_ filter was sending the wrong notification. In my tests, I could never reproduce it since I was using numerical or molecular filters. Your screencast really helped, as in the end I was very closely reproducing your actions :)

**Closed by skalkin** 2022-05-05 21:32 UTC
Labels: NX

**Comment by RobertStrulak** [comment] 2022-05-06 06:08
Great, thanks for fixing that!
