### ISSUE TITLE
Colouring is missing on adding new table view

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2052] opened 2023-06-21 07:52 UTC
Apparently Datagrok client is overriding previous set `.color-coding-type` tag on table view attach (not exactly clear which event is triggering this). This behaviour has been reproduced in Intuence Discovery as well as native Datagrok following these steps (or script):

create new table (df = grok.data.demo.geo());
assign tags to table (df.setTag('.color-coding-type', 'Conditional');
check tag (df.getTag('.color-coding-type') === 'Conditional'))
add table view: (grok.shell.addTableView(df));
wait 1 second and check tag (setTimeout(() => { grok.shell.getTag('.color-coding-type') === null), 1000);
Following script leads to same result:

//name: Column coloring issue
//description: Hello world script
//language: javascriptlet df = grok.data.demo.geo();
// add coloring
const col1 = df.col('lat');
col1.setTag('.color-coding-type', 'Conditional');
col1.setTag('.color-coding-conditional', '{"37.60 - 37.66":"#73aff5","37.66 - 37.73":"#ffa500","37.73 - 37.79":"#ff5140","37.79 - 37.85":"#50af28"}');// retrieve color tags
console.log(`.color-coding-type = ${col1.getTag('.color-coding-type')}`);
console.log(`.color-coding-conditional = ${col1.getTag('.color-coding-conditional')}`);// apply table
grok.shell.addTableView(df);
// log color tags
setTimeout(() => {
  const col2 = grok.shell.t.col('lat');
  console.log(`.color-coding-type = ${col2.getTag('.color-coding-type')}`);
  console.log(`.color-coding-conditional = ${col2.getTag('.color-coding-conditional')}`);
}, 1000);

**Comment by tcarolan** [comment] 2023-06-21 19:12
I have noticed specific color coding for String based columns does not apply on version 1.15.1. However, color coding for numbers using bins does work. I'm not sure if this was fixed in a very recent version?

**Comment by tcarolan** [comment] 2023-06-21 19:22
Checked the release notes and it appears to be fixed in 1.15.3

https://github.com/datagrok-ai/public/issues/1983

**Comment by gasserandreas** [comment] 2023-06-22 07:01
@tcarolan can you point me to the release note entry for this fix!? I am asking as we found the issue in version 1.15.3 (commit: 2b1f3c944dca9ea2b99e727fae8a63196b5475af) during testing and I am not sure if this is really fixed!

According to our research the issue is related to "something" overriding the `.color-coding-type` tag for every column somewhen during the view apply / render event (note: we have not been able to identify what exactly triggers this behaviour).

If you execute the script mentioned above, you will see that the `.color-coding-type ` is properly set to the view (first console log statements) before it get added to the view context. Checking the same tag 1 second after it was applied show's the `.color-coding-type ` being set to `null`, hence color coding is missing at all.

**Comment by tcarolan** [comment] 2023-06-22 15:52
Hello Andreas,
The fix in version 1.15.3 is not the same issue as you are reporting, although they might be related? The problem I am having it within the UI not setting color coding for Categorical columns. Here is a link to the resolved Github issue: https://github.com/datagrok-ai/public/issues/1983.
All the best,
Tom

**Comment by ahadzhanian** [comment] 2023-06-27 07:45
It is fixed in 1.15.4
![2052](https://github.com/datagrok-ai/public/assets/111368431/e1b2c03c-6b1a-4e2e-924a-4333961d65c9)

**Closed by ahadzhanian** 2023-06-27 07:45 UTC
Labels: bug, NX, high
