### ISSUE TITLE
Custom categorical columns sort order in not reflected on plots after page reload

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#718] opened 2022-06-21 11:01 UTC
**Steps to reproduce:**
1. Open some table
2. Plot some categorical column on a ScatterPlot and change its sort order to something custom
3. Save layout
4. Re-load the browser page
5. Open the same table as on step 1
6. Apply saved layout

**Expected results:** The custom sort order is correctly restored and reflected both in a table and on plots
**Actual results:** The custom sort order is not reflected on plots and is different from the table:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/15780643/174786024-d003d427-5ce4-442c-898d-a0460afeb234.png">

**Comment by onuf** [comment] 2022-07-12 13:19
@katerina-stepanova could you specify the way a layout is saved?
The order seems to be lost when saving via `View > Layout > Download`, but stays if the layout was saved via JS API (methods `saveLayout/applyLayout`, e.g., `grok.shell.v.saveLayout().toJson()`): the custom order gets applied to a scatter plot (and grid, if the sorting is applied to the column). 
Would be good to confirm that it restores properly if saved/applied via API. Meanwhile, we'll fix the behavior on `Download`.

**Comment by onuf** [comment] 2022-07-12 14:34
The specific case for `Download` is fixed in DG v1.4.15

**Comment by katerina-stepanova** [comment] 2022-07-12 15:28
@onuf I've been using 'Save' button in Layouts on the left panel:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/15780643/178527430-e75c7397-5aa2-4d7c-93d4-d7cccdd4ed70.png">

**Comment by onuf** [comment] 2022-07-12 15:31
Thanks, I'll check this one, too.

**Comment by katerina-stepanova** [comment] 2022-08-05 11:57
DG 1.5.1 : not reproduced

**Comment by onuf** [comment] 2022-08-09 11:03
I'll close the ticket in this case. @katerina-stepanova please keep an eye on the categories order, if the problem gets reproduced elsewhere, let us know.

**Closed by onuf** 2022-08-09 11:03 UTC
Labels: NX

**Comment by JianmeiFan** [comment] 2022-09-20 20:00
@onuf I tried it in https://public.datagrok.ai/ today. The custom sorting order is not reflected in table (but it's OK in scatterplot). Thanks!
