### ISSUE TITLE
Scatter plot: cannot switch axes to logarithmic scale

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#356] opened 2022-03-15 13:12 UTC
**To reproduce**
1. Open a table
2. Add a scatter plot
3. Open Properties panel
4. Switch one of the axes to logarithmic scale

**Expected results:** Axis is switched to logarithmic scale
**Actual results:** Axis is reverted to linear

Reproduced in DG v.0.130.0

**Comment by katerina-stepanova** [comment] 2022-03-17 11:42
DG 0.133: there are still issues with switching axes to logarithmic scale.

1. Properties or context menu show that axis was changed to logarithmic, but plot remains the same.
Plot is updated only on attempt to zoom it.
Reproduced in ~80% of attempts.

2. Scatter plot goes empty on switching one of the axes to logarithmic scale.
Seems to be reproduced rather randomly, issue was encountered only a few times.

**Comment by alex-aprm** [comment] 2022-03-19 22:00
I reverted the possible reason for such behavior. 
It was a code that set the default axis type on column change. 
Please, take a look at the dev server, or docker image starting from 0.136.0.

**Comment by katerina-stepanova** [comment] 2022-03-21 11:37
Issues mentioned above in relation to 0.133 are caused by negative values of an axis switched to log scale (does not make sense to switch to log scale in this case).

**Comment by skalkin** [comment] 2022-03-22 15:35
Scatter plot ignores log mode if there are negative values in the corresponding column (this is by design)

**Comment by skalkin** [comment] 2022-08-15 21:33
Looks like we are good now, then? Closing this issue.

**Closed by skalkin** 2022-08-15 21:33 UTC
Labels: NX
