### ISSUE TITLE
Summary columns cannot be added

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2275] opened 2023-08-10 09:46 UTC
v.1.15.4

**Steps to reproduce:**
1. Open a table, e.g. SPGI
2. Right click > add > summary columns

**Expected results:** Summary columns can be added: bar chart, pie chart, sparklines.
**Actual results:** Menu entries are missing:
<img width="577" alt="image" src="https://github.com/datagrok-ai/public/assets/15780643/a917eab2-c8b4-41e4-b97e-c057df625327">

**Comment by ahadzhanian** [comment] 2023-08-10 09:56
It looks like this was a regression fixed in 1.16.0
![image](https://github.com/datagrok-ai/public/assets/111368431/7995aa7e-fd71-4a1f-9ec2-d12ee7d08406)

**Closed** 2023-08-10 10:15 UTC
Labels: bug, NX
