### ISSUE TITLE
"Link Tables" does not persist when table data refreshed/reloaded

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1960] opened 2023-05-23 19:53 UTC
Load 2 tables from a database and then link them. Save the tables as a Project, close, and reopen. The linkage will be gone. This limits the ability to create a Project with many tables linked together and distribute as a finished dashboard. 

https://github.com/datagrok-ai/public/assets/6126004/5a80a200-cfc4-4b2f-b01a-0032ee102eca

**Comment by tcarolan** [comment] 2023-05-23 20:01
Maybe there is a workaround? Is the Link Tables stored as part of the Layout and can a layout be applied when opening a Project?

**Comment by ahadzhanian** [comment] 2023-05-24 08:47
Hi, Tom! You are right, linked tables should be stored in a project. Currently trying to reproduce the issue.

**Comment by ahadzhanian** [comment] 2023-05-24 09:17
We have updated the platform to version 1.15.0. And I can't reproduce the issue with saving linked tables in the project. Can you also update the platform version?

**Comment by tcarolan** [comment] 2023-05-24 16:26
Hi Olena. Tables must be "Data Sync" for the problem to arise. I will
request an upgrade. But in the meantime can you also please test in a
similar manner to the attached demo of the issue?

**Comment by ahadzhanian** [comment] 2023-05-25 08:22
Thank you for bringing my attention to the details. Here's how I reproduce linking on public.datagrok.ai:

![Linking](https://github.com/datagrok-ai/public/assets/111368431/c5ea12bb-7173-43ef-beb7-4c2840a7a70c)

**Comment by tcarolan** [comment] 2023-05-25 16:02
Thank you Olena for testing. I've requested to upgrade Datagrok to 1.15
version and once done I will report back to you if that resolves this
issue. Best regards, Tom

**Comment by tcarolan** [comment] 2023-06-06 16:00
Hello Olena, I have tested and the problem with linking tables is still present in version 1.15.1. The issue happens when data is "refreshed" OR reloaded when a project reopens (and data-synced). Please see the attached screen capture video for how to reproduce. This is a pretty big issue for my team since I can't release any data driven dashboards with multiple linked datasets. Please elevate the priority if at all possible. Thank you!
![chrome_wCODUd4k04](https://github.com/datagrok-ai/public/assets/6126004/254f91e5-b030-4239-941e-adef34b61532)

**Comment by tcarolan** [comment] 2023-06-06 16:07
It appears when refreshing data the underlying table names are not preserved. When viewing the scratchpad you can see a doubling of tables after the refresh. 

![Screenshot 2023-06-06 090343](https://github.com/datagrok-ai/public/assets/6126004/e5e95fc8-a3fe-47bb-b394-e3f2d458d7fa)

**Comment by tcarolan** [comment] 2023-06-06 22:37
html_dart2js.dart:3558 NullError: method not found: 'length' on null
	https://datagrok.neomorph.com/packages/ddt/src/utils/utils.dart 335:18                               Object.AF
	https://datagrok.neomorph.com/packages/ddt/src/data_frame/tools/link.dart 41:60                      uw.gj
	https://datagrok.neomorph.com/packages/xamgle/src/commands/data/link_tables.dart 15:20               fAl.
	https://datagrok.neomorph.com/packages/xamgle/src/commands/data/link_tables.dart 42:3                fAk
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1634:12      Object.mz
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 1490:11      Object.iy
	https://datagrok.neomorph.com/packages/xamgle/xamgle.xcmd.g.dart 858:7                               fqs.
	https://datagrok.neomorph.com/packages/ddt/src/func/func.dart 151:41                                 aNd.fi
	https://datagrok.neomorph.com/packages/ddt/src/func/func.dart 177:5                                  <fn>
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 213:19     e2W.a
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 237:5      e2W.
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 187:19     dna.
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 1128:37                              aZH
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 1012:12                              dcC.Ar
	https://datagrok.neomorph.com/packages/$sdk/lib/async/future_impl.dart 129:12                        dga.
	https://datagrok.neomorph.com/packages/$sdk/lib/async/future_impl.dart 665:13                        Object.xL
	https://datagrok.neomorph.com/packages/$sdk/lib/async/future_impl.dart 343:9                         dg1.
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 1120:12                              aZF
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 1001:12                              dcC.fF
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 901:14                               dcC.Hv
	https://datagrok.neomorph.com/packages/$sdk/lib/async/zone.dart 926:20                               dcD.
	https://datagrok.neomorph.com/packages/$sdk/lib/async/schedule_microtask.dart 41:5                   Object.e.X
	https://datagrok.neomorph.com/packages/$sdk/lib/async/schedule_microtask.dart 50:5                   h7j
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/async_patch.dart 51:9       dbn.
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48      fLQ.
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16  Od.LJ
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16   Object.G.
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14      fLO
	https://datagrok.neomorph.com/packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14      MutationObserver.<fn>

**Comment by alex-aprm** [comment] 2023-06-13 18:09
Fixed the issue with refreshing.
Will be available in the next version (1.16.x)

**Comment by ahadzhanian** [comment] 2023-07-10 13:29
Data: two tables stored in App Data, e.g. smiles.csv
project uploading breaks table linking (regardless data sync enabling)
![1960_1](https://github.com/datagrok-ai/public/assets/111368431/edc02428-7911-47ba-922c-a54ebb05b554)

**Comment by ahadzhanian** [comment] 2023-07-14 13:55
Fixed in 1.16.0

**Closed by ahadzhanian** 2023-07-14 13:55 UTC
Labels: bug, high, Neo
