### ISSUE TITLE
PowerGrid: Summary column improvements

### ISSUE THREAD

**Issue by pulveni1** [datagrok-ai/public#930] opened 2022-08-09 08:49 UTC
The new summary columns do look great, but we have a couple of improvements to suggest:

- [x] It would be nice to manage column order
- [x] Summary Columns get the standard tooltip (our natural expectation was to get the column name the bar/radar-line/line-dot represents as a tooltip "which column is that?")
- [x] It would be required to rename the summary column - it's fixed at the string 'barchart' (second one is 'barchart (2)' etc.
- [x] It would be required to be able to remove the summary column again once it's added
- [ ] It would feel it more natural to be able to add the summary columns where you can add calculated columns, and not when clicking on a grid cell
- [x] accessing settings from the hamburger menu
- [x] PieChart is not working and would need to be fixed
- [x] Add color code option to barchart and sparkline 
- [x] Remove DateTime from PowerGrid

**Comment by skalkin** [comment] 2022-09-03 19:00
Here's a new way to add summary columns:

![sparklines-from-columns](https://user-images.githubusercontent.com/943403/188284581-d942745e-6a53-4654-b53e-2ec1ffb16397.gif)

**Comment by skalkin** [comment] 2022-09-06 13:11
Closing this issue, as most of the requested features are implemented

> It would feel it more natural to be able to add the summary columns where you can add calculated columns, and not when clicking on a grid cell

Hope the new way to create sparkline columns described above works; not sure if "add new column" dialog is where it belongs. But I'm open to suggestins.

**Closed by skalkin** 2022-09-06 13:11 UTC
Labels: enhancement, NX

**Comment by katerina-stepanova** [comment] 2022-09-21 14:55
@skalkin which version of power grid are the latest changes in?

**Comment by skalkin** [comment] 2022-09-27 22:20
I think it was implemented in PowerGrid 1.1.0; the latest version is 1.1.2, I recommend using this one.

**Comment by katerina-stepanova** [comment] 2022-09-28 08:57
@skalkin 
PowerGrid 1.12: a couple of points not fixed yet
1. DateTime columns still can be added to a summary column:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/15780643/192735785-5dd47f07-96d9-416e-881c-09cd5adb2dc5.png">
2. I could not find a specific option to change columns order in a summary column. Looks like default columns order is always used, even if columns are re-arranged using 'Order or hide columns' dialog.

**Comment by katerina-stepanova** [comment] 2022-10-04 10:18
PowerGrid 1.12:
1. Summary columns are not present in 'Order or hide columns' dialog and cannot be re-ordered because of it:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/15780643/193794050-d0d3a76c-7347-40f4-8973-df9282c10a8e.png">
2. When some *other* column is hidden/shown, all summary columns disappear and cannot be restored:
![2022-10-04_13-14-38 (1)](https://user-images.githubusercontent.com/15780643/193794488-07e75c90-0f0b-4c08-a9ad-69ca5d9ea49e.gif)
3. When restored with the layout, summary column is present but its contents are not rendered:
![2022-10-04_13-17-47 (1)](https://user-images.githubusercontent.com/15780643/193795043-0cdca5cb-a9a3-4b2b-aa97-9728e1c7736f.gif)


Ticket will be re-opened.

**Comment by skalkin** [comment] 2022-10-04 12:50
> 1. DateTime columns still can be added to a summary column:

We still allow to add datetime columns manually (this could be useful is some cases), however they are not added automatically by default

**Comment by skalkin** [comment] 2022-10-04 12:54
> 1. Summary columns are not present in 'Order or hide columns' dialog and cannot be re-ordered because of it:

Good point, currently it only works with the dataframe-bound columns. Created another ticket for that: #1093

**Comment by katerina-stepanova** [comment] 2022-11-01 12:16
v1.8.2

Summary columns are still empty when saved layout is re-applied:
E.g. here 'Radar' is a summary column:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/15780643/199230440-500f0973-9a36-42a5-91e1-cdc7c962c851.png">

**Comment by skalkin** [comment] 2022-11-03 19:25
@simpleprofi , can you please take a look at it?

**Comment by skalkin** [comment] 2022-11-03 20:16
@katerina-stepanova , this is part of the PowerGrid package, do you have 1.1.6 installed? Based on your other comments, you do, but saving/restoring a layout works just fine for me. Are there any particular steps to reproduce? I would appreciate it if you show it tomorrow to @dionissqq during your weekly meeting. Thanks!

**Comment by katerina-stepanova** [comment] 2022-11-04 08:57
@skalkin yes, it's 1.1.6
I've figured out more exact steps to reproduce:
1. Open a table
2. Add a summary column
3. Save layout
4. **Refresh browser page**
5. Open the same table again
6. Apply previously saved layout

In this case summary columns are not rendered properly.
Without refreshing browser page re-applying saved layout with summary columns works fine.

**Comment by alex-aprm** [comment] 2022-11-15 13:07
Fixed in 1.8.4
