### ISSUE TITLE
Full-screen modal dialog works incorrectly

### ISSUE THREAD

**Issue by vdyma** [datagrok-ai/public#67] opened 2021-08-18 14:47 UTC
If a dialog is set to be modal **and** full screen with `.showModal(true)`, clicking outside of the dialog will result in closing it.

Example of such behavior can be found in JS API Examples: `ui/dialogs/full-screen.js`.

**Comment by skalkin** [comment] 2022-08-15 21:47
This is the intended behavior. Closing the issue, but feel free to reopen if you see reasons to change the behavior.

**Closed by skalkin** 2022-08-15 21:47 UTC
Labels: bug
