### ISSUE TITLE
Categories contain duplicate values using datadriven queries

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#2454] opened 2023-10-23 16:46 UTC
Categorical values contain duplicate values when using "DataSync=True" queries. Please see screenshots. The same data loaded from CSV does not have the same problem. Most likely due to fetch size and incorrectly loading statistics. 

![chrome_Ts5KMpb3qq](https://github.com/datagrok-ai/public/assets/6126004/3ba5a374-3d5d-4c2f-ad8b-d57ce174580a)

A 'group by' query from the data table used to make the above visualization. 
![image](https://github.com/datagrok-ai/public/assets/6126004/e0025a29-7b26-4374-be64-7a2c822c4aa1)

**Comment by skalkin** [comment] 2023-10-23 20:32
@tcarolan , thanks a lot for reporting it!
@dionissqq , I have a feeling this is due to our streaming/merging optimizations, could you please take a look?

**Comment by dionissqq** [comment] 2023-10-25 05:30
I tried some things but could not reproduce it so far. Could you provide specifics of your query, or any additional parameters that were used?

**Comment by tcarolan** [comment] 2023-11-02 23:00
Hello Denis,
Duplicate values in bar charts are still present in 1.17. Can we screenshare and I can show you? 
Tom

**Comment by skalkin** [comment] 2023-11-03 16:35
@dionissqq Let's work with Tom (or Dima, since he will be able to test from within the network on this)

@tcarolan Reopened. Damn, we were sure we fixed it in 1.7! Hopefully it will be easier this time and we include it in the next patch

**Comment by LaykDimon** [comment] 2023-11-06 18:22
The issue was fixed with the Grok Connect update to version 2.1.10

**Closed** 2023-11-06 20:12 UTC
Labels: bug, Neo
