### ISSUE TITLE
DG 1.13.13: a height of 0 is being passed to OffscreenCanvas

### ISSUE THREAD

**Issue by ptosco** [datagrok-ai/public#1829] opened 2023-04-20 17:41 UTC
@StLeonidas @MariaDolotova While testing DG 1.13.13 with `Chem. 1.5.28` we have run into this error:
![image](https://user-images.githubusercontent.com/5244385/233440968-82701cc3-8286-4a86-8c35-3f1a1b01a391.png)
What I believe happens is that `drawMoleculeToCanvas()` is passed a `0` height parameter.
In fact, first an exception is thrown here:
https://github.com/datagrok-ai/public/blob/638da4c874add9f4cbd5fde601c692f8b8ec52b0/packages/Chem/src/utils/chem-common-rdkit.ts#L132
which I can easily reproduce as follows in the console:
```
let width = 300;
let height = 0;
offscreenCanvas = new OffscreenCanvas(width, height);
mol = chem.getRdKitModule().get_mol('C');
mol.draw_to_canvas_with_highlights(offscreenCanvas, JSON.stringify({width, height}))
Uncaught 1607600
```
Then, since the molecule has failed to render, the `Chem` calls `drawErrorCross` and draws a cross on the `OffscreenCanvas` with `0` height, however, then `getImageData` fails:
https://github.com/datagrok-ai/public/blob/638da4c874add9f4cbd5fde601c692f8b8ec52b0/packages/Chem/src/utils/chem-common-rdkit.ts#L196
```
IndexSizeError: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The source height is 0.
```
This can be easily reproduced in the console with the following command:
```
offscreenCanvas.getContext('2d').getImageData(0, 0, width, height);
```
So I believe you need to investigate why `drawMoleculeToCanvas()` is passed a `0` height, and possibly clip the minimum width and height to 1 as a failsafe mechanism in case something goes wrong upstream and `0` width or height are passed.

**Comment by StLeonidas** [comment] 2023-04-20 17:56
@ptosco, yes, will fix

**Comment by MariaDolotova** [comment] 2023-04-21 07:46
Hi @ptosco ! Since we caanot reproduce this bug on our side we will need some details from you. Does this bug occur when rendering grid? Or maybe when you try to run Scaffold tree? Is this reproducing on any or some specific data? Would be great if you could provide data on which you get this error.

**Comment by ptosco** [comment] 2023-04-21 08:50
@MariaDolotova We managed to figure out where most likely the problem is.
When generating a Heat Map that includes results from R group decomposition, we see that in JSON layout the `Structure` is marked as `visible: false`, while the R group decomposition `Molecule` fields lack the `visible` attribute. As I guess `visible` defaults to `true`, the `Chem` package renderer tries to renderer them, and since they have 0 height the error I described above occurs.
```
                        "containerType": "panel",
                        "state": {
                            "width": 786,
                            "height": 364,
                            "element": {
                                "id": "8ea49b70-c640-11ed-81d1-5583344a4d0a",
                                "type": "Heat map",
                                "look": {
                                    "#type": "GridLook",
                                    "rowHeight": 100,
                                    "topLevelDefaultMenu": true,
                                    "allowColumnMenu": true,
                                    "columns": [
                                        ### SKIPPING SOME ENTRIES HERE FOR BREVITY ###
                                        {
                                            "visible": false,
                                            "width": 30,
                                            "columnName": "Structure",
                                            "cellType": "Molecule"
                                        },
                                        ### SKIPPING SOME ENTRIES HERE FOR BREVITY ###
                                        {
                                            "width": 30,
                                            "columnName": "Core",
                                            "cellType": "Molecule"
                                        },
                                        {
                                            "width": 30,
                                            "columnName": "R1",
                                            "cellType": "Molecule"
                                        },
                                        {
                                            "width": 30,
                                            "columnName": "R1-series",
                                            "cellType": "Molecule"
                                        },
```
So the proper fix is to set `visible: false` also for R group columns, but I think it woould not hurt to make the renderer robust against `w` or `h` being `0`, which should be ignored and return an empty image.

**Comment by MariaDolotova** [comment] 2023-04-21 10:14
@ptosco , you're right - this bug should be fixed on molecule renderer side. So there will be no need to mark molecule columns as not visible. I will get back to you once I fix this.

**Comment by ptosco** [comment] 2023-04-21 14:49
@MariaDolotova I don't think replacing `floor` with `ceil` will fix the problem: if height is `0`, it will stay `0`. And even if it were `0.1`, I don't think rounding it to `1` (`ceil`) rather than to `0` (`floor`) would be a good solution, as you would still waste time for rendering a molecule which would be 1-pixel wide, hence invisible. Would you like me to submit a PR with my proposal?

**Comment by MariaDolotova** [comment] 2023-04-21 15:07
@ptosco , I agree with you. Indeed there is no need to draw a molecule in case it is too small. Yes, could you please provide your decision? Is it something like lower limit for height and width? I think it makes sence

**Closed** 2023-04-25 19:13 UTC
Labels: bug, NX
