### ISSUE TITLE
Chem: Marvin sketcher doesn't set molecule after repeated opening via burger filter

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1239] opened 2022-11-30 10:23 UTC
The bug is valid for Marvin 
Steps to reproduce:
- open Marvin sketcher in burger menu of molecule column, set any molecule
- close burger panel
- open burger panel again, the molecule will be missing

**Comment by MariaDolotova** [comment] 2022-12-06 11:42
Duplicate of https://github.com/datagrok-ai/public/issues/1226

**Closed** 2022-12-06 15:22 UTC
Labels: bug
