### ISSUE TITLE
Adding a layout to project entity does not work

### ISSUE THREAD

**Issue by gasserandreas** [datagrok-ai/public#330] opened 2022-02-16 11:04 UTC
In our version of Datagrok (0.119.0) it's not possible to add and save a layout entity to the project concept.

**Methods we were using:**
`
const tableView = grok.shell.addTableView(table);
const layout = tableView.saveLayout();
project.addChild(layout);
grok.dapi.projects.save(project)
`

**Error in console**
`
Unable to add entity 5ee71bb0-8dc0-11ec-8018-1bc95c60e798 to the project
js_primitives.dart:30 null
js_primitives.dart:30 #0      ProjectsRepository.save (package:datlas/src/repositories/projects_repository.dart:69)
<asynchronous suspension>
#1      ProjectsPlugin.save.<anonymous closure> (package:datlas/src/plugins/projects.dart:198)
<asynchronous suspension>
#2      DbContext.run.<anonymous closure> (package:datlas/src/db_context.dart:375)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1001)
#5      runZoned (dart:async/zone.dart:1467)
#6      DbContext.run (package:datlas/src/db_context.dart:374)
<asynchronous suspension>
#7      GrokServerDbPlugin.dbRun (package:datlas/src/grok_server_plugin.dart:88)
<asynchronous suspension>
#8      ProjectsPlugin.save (package:datlas/src/plugins/projects.dart:195)
#9      _LocalInstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:526)
#10     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:522)
#11     _LocalClosureMirror.apply (dart:mirrors-patch/mirrors_impl.dart:550)
#12     ConstrainedFunctionProxy.invoke (package:constrain/constrained_function_proxy.dart:41)
#13     _wrapHandler.<anonymous closure> (package:shelf_bind/src/model/handler_bindings.dart:119)
<asynchronous suspension>
#14     HandlerBinding._handleRequest (package:shelf_bind/src/model/handler_bindings.dart:78)
#15     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
<asynchronous suspension>
#16     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
#17     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112)
#18     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
<asynchronous suspension>
#19     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
#20     _BaseRoute.createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:32)
<asynchronous suspension>
#21     GrokServer.authorize.<anonymous closure>.inner.<anonymous closure> (package:datlas/src/grok_server.dart:503)
#22     _rootRun (dart:async/zone.dart:1120)
#23     _CustomZone.run (dart:async/zone.dart:1001)
#24     runZoned (dart:async/zone.dart:1467)
#25     GrokServer.authorize.<anonymous closure>.inner (package:datlas/src/grok_server.dart:501)
#26     GrokServer.authorize.<anonymous closure> (package:datlas/src/grok_server.dart:553)
<asynchronous suspension>
#27     logRequests.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:datlas/src/errors.dart:130)
#28     new Future.sync (dart:async/future.dart:206)
#29     logRequests.<anonymous closure>.<anonymous closure> (package:datlas/src/errors.dart:130)
#30     GrokServer.statistics.<anonymous closure> (package:datlas/src/grok_server.dart:436)
<asynchronous suspension>
#31     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
#32     new Future.sync (dart:async/future.dart:206)
#33     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
#34     _rootRunUnary (dart:async/zone.dart:1128)
#35     _CustomZone.runUnary (dart:async/zone.dart:1012)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#37     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#38     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#39     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
#40     _rootRun (dart:async/zone.dart:1120)
#41     _CustomZone.run (dart:async/zone.dart:1001)
#42     _CustomZone.runGuarded (dart:async/zone.dart:901)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
`

**Comment by alex-aprm** [comment] 2022-02-22 20:07
@gasserandreas Can you check in 125.4? Seems, it's already fixed

**Comment by skalkin** [comment] 2022-03-22 14:44
Closing since there was no further input. @gasserandreas , please reopen if the issue is still there.

**Closed by skalkin** 2022-03-22 14:44 UTC
Labels: NX
