### ISSUE TITLE
Chem | Top menu Sketcher: works with blank data

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1327] opened 2022-12-09 13:33 UTC
Platform: public "Version":"1.10.2"
Data: [smiles](https://public.datagrok.ai/f/System.AppData/Chem/smiles.csv)

To reproduce:

1. Go to Chem > Sketcher.
2. For empty sketcher, click Filter. 
Actual: empty dataframe
Expected: Sketcher doesn’t work with blank data

![Image](https://user-images.githubusercontent.com/111368431/206713662-1e52a01b-482e-48e4-bf3e-dd10d75b87f5.gif)

**Comment by MariaDolotova** [comment] 2023-01-09 13:35
Duplicate of #1324

**Comment by MariaDolotova** [comment] 2023-04-21 12:07
No relevant any more

**Closed by MariaDolotova** 2023-04-21 12:07 UTC
Labels: bug
