### ISSUE TITLE
Chem top menu bug

### ISSUE THREAD

**Issue by StLeonidas** [datagrok-ai/public#1224] opened 2022-11-24 08:23 UTC
Top menu item "Chem" does not appear if "Menu is not activated".
Could be reproduced on the datasets with a single Molecule column

![image](https://user-images.githubusercontent.com/57249456/203730095-5797b5df-e023-4bcd-9584-543c68f7af0e.png)

**Comment by skalkin** [comment] 2022-11-26 15:12
> Top menu item "Chem" does not appear if "Menu is not activated".

I don't get it, can you please elaborate?

**Comment by StLeonidas** [comment] 2022-11-28 08:41
In some cases Chem appears in top menu only when "menu" button is clicked

![image](https://user-images.githubusercontent.com/57249456/204232126-5413e7f9-472a-4bbd-b30c-210d92dee2ab.png)

**Comment by skalkin** [comment] 2022-11-28 16:01
@StLeonidas , can you reproduce it on the latest dev?

**Comment by StLeonidas** [comment] 2022-11-28 16:20
I cannot reproduce it on dev now, though closing menu leads to all top menu vanishing (again for tables with 1 column)
![image](https://user-images.githubusercontent.com/57249456/204328337-092f7abc-7899-4da9-a947-1fe94cea4af6.png)

**Comment by alex-aprm** [comment] 2024-02-06 15:39
Looks like it is a side effect of power-pack. Investigating...

**Comment by alex-aprm** [comment] 2024-02-06 15:43
Fixed in PowerPack 1.2.0

**Closed by alex-aprm** 2024-02-06 15:43 UTC
Labels: bug, VS

**Comment by dnillovna** [comment] 2024-02-13 09:56
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-14933
