### ISSUE TITLE
Changing the order of values of categorical columns is not reflected in the filter panel

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#576] opened 2022-05-11 08:40 UTC
**Steps to reproduce:**
1. Open the filter panel and ensure that the categorical column you are about to modify is added as a filter
2. Change the order of values of the previously mentioned categorical column (right click on the column header -> sort -> custom)
3. Filter out one of swapped values from the 2nd step

**Expected result:**
1. The values are correctly filtered out

**Current result:**
1. The wrong value is being filtered out (values in the filter panel are based on the initial order that is not updated after creating custom order)

https://user-images.githubusercontent.com/99964535/167807072-bd349526-375d-4cec-9025-cb07ffc0dd32.mp4

**Work around:**
- Change the custom order with the closed filter panel
- Close & reopen the filter panel when the modification was made while it was opened

**Comment by skalkin** [comment] 2022-05-17 14:12
Found out the root cause, but handling it properly will take some time. Estimate: 5/22/2022

**Comment by RobertStrulak** [comment] 2022-05-24 14:59
@skalkin - on priority

**Comment by skalkin** [comment] 2022-06-06 21:57
Fixed in Datagrok v1.1.8

**Closed by skalkin** 2022-06-06 21:57 UTC
Labels: NX
