### ISSUE TITLE
Zoom Sliders get reset on the Scatter Plot (Zoom And Filter: no action, Axes Follow Filter: false) on opening the filter panel with some filtering applied

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#552] opened 2022-05-04 11:07 UTC
**Steps to reproduce:**

1. Open a project and add a Scatter Plot (**Zoom And Filter: no action**, **Axes Follow Filter: false**)
2. Modify Zoom Sliders
3. Open the filter panel and apply some filtering
4. Close and reopen the filter panel

**Expected result:**
Zoom Sliders are not reset

**Current result:**
Zoom Sliders get reset on opening the filter panel with some filtering applied
![2022-05-04_12-52-36](https://user-images.githubusercontent.com/99964535/166669690-5ccbb440-083f-4e7a-b3db-6fce96d1f6b6.gif)

**Comment by skalkin** [comment] 2022-05-05 21:31
Fixed in v150.7

Bingo! Looks like I have found the issue - the root of the problem was that the _categorical_ filter was sending the wrong notification. In my tests, I could never reproduce it since I was using numerical or molecular filters. Your screencast really helped, as in the end I was very closely reproducing your actions :)

**Closed by skalkin** 2022-05-05 21:31 UTC

**Comment by RobertStrulak** [comment] 2022-05-06 06:07
Great, I'm glad it was helpful! Thanks Andrew for such a quick reaction!
