### ISSUE TITLE
Items are unexpectedly filtered out after new rows were added

### ISSUE THREAD

**Issue by RobertStrulak** [datagrok-ai/public#383] opened 2022-03-24 22:20 UTC
**Steps to reproduce:** 

1. Open a project
2. Open filter panel
3. Make sure it contains a categorical filter or a range filter for column with values for most of the rows 
4. Make sure nothing is filtered
5. Save layout
6. Modify underlying data source that will result in adding new rows
7. Reopen project

**Expected results:** All rows are shown when project is opened. No filtering is enabled.

**Actual results:** Newly added rows are filtered out.

**Comment by skalkin** [comment] 2022-03-26 15:04
Fixed in v0.140

The problem was due to the fact that filter state (per NIBR request) is now saved as part of the layout, and apparently the new row does not satisfy the filter. I have added a heuristic that filter state only gets saved if a user has manually modified the filter, but of course this might also lead to unexpected behavior; there is no way around it.

**Closed by skalkin** 2022-03-26 15:04 UTC
Labels: NX

**Comment by RobertStrulak** [comment] 2022-03-28 06:00
Hi Andrew,
Just to be clear, does the solution you described cover this case?
1. User deselects a value in a filter for given column
2. User selects that value again resulting in all rows selected for a filter
3. New rows are added

The main question is about this part " filter state only gets saved if a user has manually modified the filter". 
Do any modifications (even ones that are reverting each other, like something was deselected and selected) result in saving the state of the filter panel? 

The expected behavior from our end is that if all rows are selected for given filter no matter what will happen with a data (rows were added / removed) all will be always all.

**Comment by skalkin** [comment] 2022-04-01 11:48
Hi @RobertStrulak , yes it works the way you described it.
