### ISSUE TITLE
Tag .color-coding-categorical is missing on a column if default categorical colours are used

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1147] opened 2022-10-26 07:52 UTC
**Steps to reproduce:**
1. Open a table
2. Apply categorical colouring to some column
3. Go to column properties and see tags

**Expected results:** .color-coding-categorical and .color-coding-type tags are present
**Actual results:** only .color-coding-type is present. Tag .color-coding-categorical is added only if colours are customised.

**Comment by skalkin** [comment] 2022-11-01 15:32
Is it a bug though?

**Comment by skalkin** [comment] 2022-11-01 16:53
@onuf will provide a way to retrieve the default palette, in case `.color-coding-categorical` is not specified (this is an optimization, not a bug)

**Comment by onuf** [comment] 2022-11-01 18:12
Here it is: https://datagrok.ai/js-api/classes/dg.Color#categoricalPalette

**Comment by madmurdok** [comment] 2022-11-02 08:14
@onuf So, if there is no .color-coding-categorical tag, but .color-coding-type means that we use categorical colors => we can use categoricalPalette for getting default colors?

**Comment by skalkin** [comment] 2022-11-06 23:28
Closing this issue, please reopen if more assistance is needed

**Closed by skalkin** 2022-11-06 23:28 UTC
Labels: NX
